#Processing --> python mode



class Rectangle:
    def __init__(self, x, y, w, h):
        self.x = x
        self.y = y
        self.w = w
        self.h = h
        
    def move(self, x, y):
        self.x = x
        self.y = y
    
    def display(self):
        rect(self.x, self.y, self.w, self.h)

myrect = Rectangle(0, 0, 50, 50)

def draw():
    background(255)
    fill(255, 0, 0)
    myrect.move(mouseX, mouseY)
    myrect.display()
