
mode=Python
mode.id=jycessing.mode.PythonMode

def draw():
    stroke(0)
    line(0, 0, 400, 400)
    stroke(255, 100, 150) #pink color
    line(400, 0, mouseX, mouseY)
    noFill()
    rect(200, 200, 100, 50)
